INSERT INTO jobs (position,
                  overview,
                  responsibilities,
                  qualifications,
                  benefits,
                  skills,
                  company_name,
                  company_logo_url,
                  company_location,
                  apply_url,
                  job_types,
                  job_location,
                  salary_range,
                  create_at,
                  update_at)
VALUES
-- 1
('Senior Frontend Developer', 'Build and optimize modern web UIs',
 'Implement features, performance tuning, code review',
 '5+ years FE, strong TypeScript/React',
 'Health, stock options, learning budget',
 'React, TypeScript, Vite, CSS',
 'Acme Web',
 'https://placehold.co/80x80?text=AC',
 'San Francisco, CA',
 'https://jobs.example.com/apply/101',
 'full-time',
 'hybrid',
 '$120,000 - $150,000',
 NOW(), NOW()),
-- 2
('Backend Engineer', 'Own APIs and services at scale',
 'Design APIs, optimize DB, write tests',
 'Proficient in Node.js and SQL',
 '401k match, remote stipend',
 'Node.js, PostgreSQL, Redis, Docker',
 'CoreStack',
 'https://placehold.co/80x80?text=CS',
 'Austin, TX',
 'https://jobs.example.com/apply/102',
 'full-time',
 'remote',
 '$120,000 - $150,000',
 NOW(), NOW()),
-- 3
('Full Stack Developer', 'Ship end-to-end features',
 'Build UI and APIs, CI/CD, reviews',
 '3+ years web dev, security basics',
 'Flexible hours, equipment budget',
 'React, Node.js, TypeScript',
 'NovaLabs',
 'https://placehold.co/80x80?text=NL',
 'Remote',
 'https://jobs.example.com/apply/103',
 'full-time',
 'remote',
 '$100,000 - $120,000',
 NOW(), NOW()),
-- 4
('Mobile Engineer (React Native)', 'Deliver high-quality mobile apps',
 'Implement features, crash monitoring',
 'Launched RN apps preferred',
 'Health, device stipend, PTO',
 'React Native, TypeScript',
 'PocketWave',
 'https://placehold.co/80x80?text=PW',
 'New York, NY',
 'https://jobs.example.com/apply/104',
 'full-time',
 'in-person',
 '$120,000 - $150,000',
 NOW(), NOW()),
-- 5
('DevOps Engineer', 'Scale CI/CD and infra',
 'Automate pipelines, observability, IaC',
 'Linux + cloud experience',
 'Remote-friendly, on-call stipend',
 'AWS, Kubernetes, Terraform',
 'InfraSeed',
 'https://placehold.co/80x80?text=IS',
 'Remote',
 'https://jobs.example.com/apply/105',
 'full-time',
 'remote',
 '$120,000 - $150,000',
 NOW(), NOW()),
-- 6
('Site Reliability Engineer', 'Improve reliability and latency',
 'Incident response, capacity planning',
 'SRE practices, monitoring tools',
 'Equity, wellness stipend',
 'SRE, Prometheus, Grafana, Go',
 'UptimeHQ',
 'https://placehold.co/80x80?text=UH',
 'Seattle, WA',
 'https://jobs.example.com/apply/106',
 'full-time',
 'hybrid',
 '$150,000 - $250,000',
 NOW(), NOW()),
-- 7
('Data Engineer', 'Build robust data pipelines',
 'ETL, data modeling, governance',
 'Modern data stack experience',
 'Conference budget, PTO',
 'Python, SQL, Airflow, dbt',
 'DataForge',
 'https://placehold.co/80x80?text=DF',
 'Boston, MA',
 'https://jobs.example.com/apply/107',
 'full-time',
 'hybrid',
 '$120,000 - $150,000',
 NOW(), NOW()),
-- 8
('Data Scientist', 'Create insights and models',
 'EDA, model training, reporting',
 'Statistics/ML background',
 'Research budget, flexible PTO',
 'Python, Pandas, scikit-learn',
 'Insightlytics',
 'https://placehold.co/80x80?text=IL',
 'Chicago, IL',
 'https://jobs.example.com/apply/108',
 'full-time',
 'in-person',
 '$120,000 - $150,000',
 NOW(), NOW()),
-- 9
('Machine Learning Engineer', 'Productionize ML at scale',
 'Feature store, serving, monitoring',
 'MLOps and distributed systems',
 'Equity, health insurance',
 'PyTorch, TensorFlow, K8s',
 'ModelFlow',
 'https://placehold.co/80x80?text=MF',
 'Remote',
 'https://jobs.example.com/apply/109',
 'full-time',
 'remote',
 '$150,000 - $250,000',
 NOW(), NOW()),
-- 10
('Product Manager', 'Lead product discovery/delivery',
 'Roadmaps, experiments, metrics',
 '4+ years PM, research skills',
 'Bonus, learning stipend',
 'Product strategy, Analytics',
 'BrightPath',
 'https://placehold.co/80x80?text=BP',
 'Denver, CO',
 'https://jobs.example.com/apply/110',
 'full-time',
 'hybrid',
 '$120,000 - $150,000',
 NOW(), NOW()),
-- 11
('Technical Product Manager', 'Drive technical initiatives',
 'Requirements, backlog, alignment',
 'Technical background a plus',
 'Health, equity',
 'APIs, Cloud, Agile',
 'TechScope',
 'https://placehold.co/80x80?text=TS',
 'San Jose, CA',
 'https://jobs.example.com/apply/111',
 'full-time',
 'in-person',
 '$120,000 - $150,000',
 NOW(), NOW()),
-- 12
('UI/UX Designer', 'Design accessible experiences',
 'User flows, prototypes, testing',
 'Design systems experience',
 'Design tools budget',
 'Figma, Prototyping, A11y',
 'CanvasLab',
 'https://placehold.co/80x80?text=CL',
 'Los Angeles, CA',
 'https://jobs.example.com/apply/112',
 'full-time',
 'hybrid',
 '$100,000 - $120,000',
 NOW(), NOW()),
-- 13
('Product Designer', 'Own end-to-end product design',
 'Research, high-fidelity design',
 'Strong portfolio required',
 'Remote-first, wellness stipend',
 'Figma, UX Research, Systems',
 'Orbit Design',
 'https://placehold.co/80x80?text=OD',
 'Remote',
 'https://jobs.example.com/apply/113',
 'full-time',
 'remote',
 '$100,000 - $120,000',
 NOW(), NOW()),
-- 14
('QA Engineer', 'Ensure product quality',
 'Test plans, automation, reports',
 'Experience with test frameworks',
 'Flexible PTO, remote',
 'Playwright, Cypress, Jest',
 'QualityNest',
 'https://placehold.co/80x80?text=QN',
 'Phoenix, AZ',
 'https://jobs.example.com/apply/114',
 'full-time',
 'hybrid',
 '$70,000 - $100,000',
 NOW(), NOW()),
-- 15
('Security Engineer', 'Elevate app security posture',
 'Threat modeling, code reviews',
 'Security certs a plus',
 'Learning budget, on-call',
 'OWASP, SAST, DAST',
 'ShieldOps',
 'https://placehold.co/80x80?text=SO',
 'Austin, TX',
 'https://jobs.example.com/apply/115',
 'full-time',
 'in-person',
 '$120,000 - $150,000',
 NOW(), NOW()),
-- 16
('Cloud Architect', 'Design cloud architectures',
 'Networking, cost optimization',
 'Deep cloud expertise',
 'Equity, wellness stipend',
 'AWS, VPC, Terraform',
 'SkyArc',
 'https://placehold.co/80x80?text=SA',
 'Remote',
 'https://jobs.example.com/apply/116',
 'full-time',
 'remote',
 '$150,000 - $250,000',
 NOW(), NOW()),
-- 17
('Solutions Architect', 'Guide customers to success',
 'Discovery, solution design, POC',
 'Excellent communication',
 'Travel stipend, bonus',
 'Pre-sales, Architecture',
 'ClientWorks',
 'https://placehold.co/80x80?text=CW',
 'New York, NY',
 'https://jobs.example.com/apply/117',
 'full-time',
 'hybrid',
 '$120,000 - $150,000',
 NOW(), NOW()),
-- 18
('Customer Success Manager', 'Drive adoption and retention',
 'Onboarding, QBRs, renewals',
 'Empathy and problem-solving',
 'Flexible PTO, remote',
 'CRM, Analytics, Enablement',
 'CareBridge',
 'https://placehold.co/80x80?text=CB',
 'Remote',
 'https://jobs.example.com/apply/118',
 'full-time',
 'remote',
 '$70,000 - $100,000',
 NOW(), NOW()),
-- 19
('Technical Writer', 'Produce clear developer docs',
 'Tutorials, guides, release notes',
 'Experience writing for devs',
 'Book budget, flexible hours',
 'Docs-as-code, Markdown, APIs',
 'DocuCraft',
 'https://placehold.co/80x80?text=DC',
 'Seattle, WA',
 'https://jobs.example.com/apply/119',
 'part-time',
 'hybrid',
 '$50,000 - $70,000',
 NOW(), NOW()),
-- 20
('Junior Frontend Developer', 'Support UI development',
 'Implement components, fix bugs',
 'Basic React knowledge',
 'Mentorship, learning budget',
 'React, CSS, Testing',
 'Startline',
 'https://placehold.co/80x80?text=SL',
 'Remote',
 'https://jobs.example.com/apply/120',
 'full-time',
 'remote',
 '$70,000 - $100,000',
 NOW(), NOW());
